<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta name="robots" content="noindex, nofollow">

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Validation against FOCUS · difes test ledger – difes · the test ledger</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-afe927e19676d0e50b1726048be49fb1.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700&amp;family=Source+Sans+3:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=IBM+Plex+Mono:wght@400;500&amp;display=swap" rel="stylesheet">
<!-- KaTeX auto-render: publication titles carry TeX inside generated HTML that
     Quarto's own math pipeline never sees (same approach as thermomat). -->
<script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
<script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script>
<script defer="" src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"></script>
<script>
/* The header ribbon is sticky; the side columns and anchor targets need its height. */
(function () {
  function headH() {
    var t = document.querySelector(".topline"), h = document.querySelector(".site-head");
    var px = (t ? t.offsetHeight : 0) + (h ? h.offsetHeight : 0);
    if (px) document.documentElement.style.setProperty("--head-h", px + "px");
  }
  document.addEventListener("DOMContentLoaded", headH);
  window.addEventListener("load", headH);
  window.addEventListener("resize", headH);
})();
document.addEventListener("DOMContentLoaded", function () {
  if (window.renderMathInElement) {
    renderMathInElement(document.body, {
      delimiters: [{ left: "$$", right: "$$", display: true }, { left: "$", right: "$", display: false }, { left: "\\(", right: "\\)", display: false }],
      throwOnError: false
    });
  }
  /* Quarto's KaTeX pipeline writes <span class="math inline">TeX</span> without delimiters and renders
     them in a loop that reads firstChild.data; that loop dies at the first span the auto-render above
     has already turned into KaTeX markup, leaving every later formula raw. Render the rest here. */
  if (window.katex) {
    document.querySelectorAll(".math").forEach(function (el) {
      if (!el.querySelector(".katex")) {
        var t = el.textContent.replace(/^\s*\\[\(\[]/, "").replace(/\\[\)\]]\s*$/, "");
        try { katex.render(t, el, { displayMode: el.classList.contains("display"), throwOnError: false }); } catch (e) {}
      }
      /* Quarto's loop would still visit this span and wipe it (firstChild is now an element, not text):
         take it out of its sight. No stylesheet of the site depends on the class; KaTeX's own output carries the layout. */
      el.classList.remove("math"); el.classList.add("math-done");
    });
  }
});
</script>

  <script defer="" src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/styles/theme.css">
<link rel="stylesheet" href="../assets/styles/site.css">
<link rel="stylesheet" href="../assets/styles/twin.css">
</head>

<body>

<!-- Header of the twin site: the test ledger published on its own. The entries are the groups of
     data/nav-twin.yml, in the same order. -->
<div class="topline"></div>
<header class="site-head">
  <div class="site-head__inner">
    <a href="../index.html" class="wordmark">difes <span class="accent">test</span> ledger
      <span class="wordmark-sub">Every check of the program, graded, with the validation pages and the manual · a twin of the project site, regenerated with it</span>
    </a>
    <nav class="site-nav">
      <a href="../tests/index.html">Ledger</a>
      <a href="../validation/index.html">Validation</a>
      <a href="../manual/index.html">Manual</a>
      <span class="nav-right">
        <a href="../assets/documents/test-ledger.pdf" class="nav-dl">Ledger as PDF</a>
      </span>
    </nav>
  </div>
</header>
<!-- generated by tools/build.py: left navigation + opening of the reading column -->
<div class="docs">
<nav class="docs-nav" aria-label="Site sections">
<button class="docs-fold" type="button" data-fold="nav" aria-label="Hide the navigation" title="Hide the navigation">‹</button>
<details class="group" open=""><summary class="t">Ledger</summary><ul><li><a href="../tests/index.html">The test ledger, difes's presentation card</a></li></ul></details>
<details class="group" open=""><summary class="t">Validation</summary><ul><li><a href="../validation/index.html">Against FOCUS, on Irati's data</a></li><li><a href="../validation/irati-path.html">Irati's path, step by step</a></li><li><a href="../validation/papers.html">Published works, solved again</a></li><li><a href="../validation/focus-samples.html">FOCUS's own sample projects</a></li><li><a href="../validation/literature.html">The FOCUS literature, reproduced</a></li></ul></details>
<details class="group" open=""><summary class="t">Manual</summary><div class="sub"><div class="st">Using difes</div><ul><li><a href="../manual/index.html">About the manual</a></li><li><a href="../manual/user/getting-started.html">Getting started</a></li><li><a href="../manual/user/spectra-models.html">Spectra and models</a></li><li><a href="../manual/user/simulate-fit.html">Simulating and fitting</a></li><li><a href="../manual/user/kramers-kronig.html">Kramers–Kronig and CFRC</a></li><li><a href="../manual/user/language-sessions.html">Formulas, sessions, views, libraries</a></li><li><a href="../manual/user/focus-exchange.html">Exchanging with FOCUS</a></li><li><a href="../manual/user/reffit.html">Exchanging with RefFIT</a></li><li><a href="../manual/user/receive.html">Receiving a colleague's folder</a></li><li><a href="../manual/user/shell.html">The shell</a></li><li><a href="../manual/user/bench.html">The Bench</a></li><li><a href="../manual/user/digitise.html">Digitising figures</a></li><li><a href="../manual/user/api.html">Python reference</a></li></ul></div><div class="sub"><div class="st">Theoretical basis</div><ul><li><a href="../manual/theory/index.html">Scope and conventions</a></li><li><a href="../manual/theory/response.html">The dielectric response</a></li><li><a href="../manual/theory/models.html">Models of the dielectric function</a></li><li><a href="../manual/theory/optics.html">From $\varepsilon$ to the measured spectrum</a></li><li><a href="../manual/theory/kramers-kronig.html">Kramers–Kronig on a finite range</a></li><li><a href="../manual/theory/fitting.html">Least-squares fitting</a></li><li><a href="../manual/theory/uncertainty.html">Uncertainties, following the GUM</a></li><li><a href="../manual/theory/instrument.html">The measurement</a></li><li><a href="../manual/theory/references.html">References</a></li></ul></div></details>
<details class="group" open=""><summary class="t">Documents</summary><ul><li><a href="../assets/documents/test-ledger.pdf">The test ledger (PDF)</a></li><li><a href="../assets/documents/validation-focus.pdf">difes against FOCUS, for Irati (PDF)</a></li></ul></details>
</nav>
<div class="docs-main">

<header id="title-block-header">
<h1 class="title">Validation against FOCUS</h1>
<p class="subtitle">Does difes, used the way Irati used FOCUS, give her results? Four levels, from the exact to the procedural, on the group’s own chromium data.</p>

</header>


<p class="lede">The question that started this project was whether a tool of our own could do what FOCUS did for the TFG. With Irati's two project files exported from FOCUS (log L039) and the report's tables and curve, the test can now be run end to end: the same spectra, the same models, the same ranges, the same film formula. The script is <code>difes/examples/reproduce_irati.py</code>; every number below comes from one run of it (difes 0.14.0, 1 October 2026).</p>
<p class="lede" style="font-size:.95em"><b>As documents:</b> <a href="../assets/documents/validation-focus.pdf">difes against FOCUS (PDF, 7 pages)</a>, this page and <a href="irati-path.html">Irati's path</a> condensed for sharing, with the figures and the files used; and <span class="offsite" title="On the ftir apps ecosystem site, the project&#x27;s working site, which is not published yet">difes and FOCUS: where the comparison stands (PDF, 3 pages)</span>, the brief for the group's FOCUS expert: what has been checked, what is open, two requests.</p>
<h2 id="what-reproduce-can-mean" class="anchored">What “reproduce” can mean</h2>
<p>A fit program gives three things: the curve it draws for a model, the parameters it stops at, and the way a person reaches them. These are not equally reproducible, and the report itself says so about the second: the second Drude term of chromium “is not entirely sensible”, and the oxide fit “does not reach the 550 <span class="math inline">\mathrm{cm}^{-1}</span> peak” and “fails at the edges”. So the test is layered:</p>
<ul>
<li><strong>A. Forward optics</strong> — same parameters, same curve. This must be exact.</li>
<li><strong>B, C. The fit as a minimisation</strong> — from the report’s values and from elsewhere, does difes’s fitter find the same curve, and the same parameters where the problem is well posed?</li>
<li><strong>D. The procedure</strong> — the Bench recipes (import, model, film sample, guided fit, adopt) on the emissivity itself, as a student would do it.</li>
</ul>
<figure>
<img src="../assets/figures/reproduce_irati.png" alt="Four panels: forward optics, pure chromium fits, oxide film refit, the Bench's guided fit" style="width:100%; border:1px solid var(--line, #ddd);">
<figcaption>A: FOCUS's own film formula from Bestebat.sml and difes's film optics with the FOCUS form coincide; the report's model against FOCUS's drawn curve. B: pure chromium, the Table 4 curve and difes's fits from a generic start under two weightings. C: the oxide film, Table 6 as transcribed and difes's refit from it. D: the Bench's guided fit on the emissivity from Table 6 and from the Bench's own suggestions.</figcaption>
</figure>
<h2 id="a.-forward-optics-exact-once-the-formula-is-the-same" class="anchored">A. Forward optics: exact, once the formula is the same</h2>
<p>FOCUS’s project files hold the formulas FOCUS computes. Evaluating them in difes’s math language and comparing with difes’s own sample optics at identical parameters:</p>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">quantity (Bestebat.sml, 400–1350 <span class="math inline">\(\mathrm{cm}^{-1}\)</span>)</th>
<th data-quarto-table-cell-role="th">difes form</th>
<th data-quarto-table-cell-role="th">rms difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>bare chromium, Fresnel reflectance</td>
<td>—</td>
<td><span class="math inline">\(1.5\times10^{-16}\)</span></td>
</tr>
<tr class="even">
<td>0.8 <span class="math inline">\(\mu\)</span>m incoherent oxide film</td>
<td><code>focus</code> (eq. 27)</td>
<td><span class="math inline">\(1.7\times10^{-16}\)</span></td>
</tr>
<tr class="odd">
<td>0.8 <span class="math inline">\(\mu\)</span>m incoherent oxide film</td>
<td><code>energy</code> (default)</td>
<td><span class="math inline">\(8.8\times10^{-3}\)</span>, max 0.049</td>
</tr>
</tbody>
</table>

</div>
<p>The finding of this level is the third row. FOCUS’s incoherent film, the <code>Reflectance-Ei-E1-E2</code> symbol and eq. 27 of the report, writes the numerator as <span class="math inline">|(1 - r_1^2)\, r_2\, \tau^2|^2</span>, the product of amplitude transmittances; difes’s default writes <span class="math inline">(1 - R_1)^2 R_2 A</span>, the energy-conserving intensity form. They coincide when the film’s index is real and differ where the film absorbs, up to 0.05 in the reststrahlen band of <span class="math inline">\mathrm{Cr_{2}O_{3}}</span>. difes 0.14.0 offers both (<code>form="focus"</code> on the sample, the <strong>formula</strong> selector of the Bench’s Sample card), so a FOCUS result can be reproduced to machine precision, and the manual’s earlier claim that the two forms agree to better than 1 % is withdrawn for strongly absorbing films.</p>
<p>A second forward check uses the report rather than the files: Table 4 and Table 6 (fourteen Lorentz oscillators, <span class="math inline">\omega_0</span> of the fourth not transcribed) on an incoherent film of thickness not stated. Fitting only those two unknowns against FOCUS’s drawn curve of figure 20 (<code>curve.dat</code>):</p>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">film form</th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\omega_0\)</span> of oscillator 4</th>
<th data-quarto-table-cell-role="th">thickness</th>
<th data-quarto-table-cell-role="th">rms vs curve.dat</th>
<th data-quarto-table-cell-role="th">above 450 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>energy</code></td>
<td>625.0 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></td>
<td>1.093 <span class="math inline">\(\mu\)</span>m</td>
<td><span class="math inline">\(9.9\times10^{-3}\)</span></td>
<td><span class="math inline">\(3.7\times10^{-3}\)</span></td>
</tr>
<tr class="even">
<td><code>focus</code></td>
<td>624.7 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></td>
<td>1.196 <span class="math inline">\(\mu\)</span>m</td>
<td><span class="math inline">\(1.8\times10^{-2}\)</span></td>
<td><span class="math inline">\(1.6\times10^{-2}\)</span></td>
</tr>
</tbody>
</table>

</div>
<p>The report’s curve is reproduced to the precision of the transcribed parameters by the energy form, not by the form the exported files use. Either the report’s figure was drawn with a different film symbol than the later files, or the fourteen tabulated parameters are rounded in a way that happens to favour the energy form; the 400–450 <span class="math inline">\mathrm{cm}^{-1}</span> edge, where neither form follows the curve, points to a term below the range.</p>
<p><strong>Settled on 2 October with FOCUS’s own output.</strong> Irati exported three curves of Azkena.sml from FOCUS (<code>Azkena-PhysRev_doitzeko.dat</code>, <code>Azkena-oxido.dat</code>, <code>Azkena-teoriko_monokristal.dat</code>, 512 points on 0–1500 <span class="math inline">\mathrm{cm}^{-1}</span>, seven significant digits). difes evaluates the same definitions from the same file:</p>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">FOCUS export</th>
<th data-quarto-table-cell-role="th">difes definition</th>
<th data-quarto-table-cell-role="th">max |<span class="math inline">\(\Delta\)</span>|</th>
<th data-quarto-table-cell-role="th">what that is</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Azkena-PhysRev_doitzeko</td>
<td><code>R_PhysRev_doitzeko</code> (the final reflectance)</td>
<td><span class="math inline">\(5.6\times10^{-6}\)</span> (rms <span class="math inline">\(8.6\times10^{-7}\)</span>)</td>
<td>the seven-digit rounding of the file</td>
</tr>
<tr class="even">
<td>Azkena-teoriko_monokristal, Azkena-oxido (identical files)</td>
<td><code>Funtzio_dielektrikoa_PhysRev</code> (<span class="math inline">\(\varepsilon\)</span> of the single-crystal model)</td>
<td><span class="math inline">\(4.4\times10^{-5}\)</span> relative</td>
<td>the same rounding, on values up to 128</td>
</tr>
</tbody>
</table>

</div>
<p>Number against number, nothing transcribed, nothing guessed: level A is exact. The comparison is a test of the package and the fifth step of <a href="irati-path.html">Irati’s path</a>.</p>
<h2 id="b.-pure-chromium-the-curve-is-reproduced-the-parameters-are-not-unique" class="anchored">B. Pure chromium: the curve is reproduced, the parameters are not unique</h2>
<p>The report fits <span class="math inline">\varepsilon_\infty</span> plus two Drude terms to <span class="math inline">R = 1 - E</span> of the pure sample at 500 °C and 10°, excluding the 1200–2400 <span class="math inline">\mathrm{cm}^{-1}</span> dip it attributes to the measurement. On the same 545 points:</p>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">weights</th>
<th data-quarto-table-cell-role="th">start</th>
<th data-quarto-table-cell-role="th">rms vs data</th>
<th data-quarto-table-cell-role="th">rms vs the Table 4 curve</th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\varepsilon_\infty\)</span></th>
<th data-quarto-table-cell-role="th"><span class="math inline">\((\omega_p, \gamma)_1\)</span></th>
<th data-quarto-table-cell-role="th"><span class="math inline">\((\omega_p, \gamma)_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td colspan="2">Table 4 itself</td>
<td>0.0075</td>
<td>—</td>
<td>4.86</td>
<td>(15344, 834)</td>
<td>(26930, 14258)</td>
</tr>
<tr class="even">
<td>measured <span class="math inline">\(\sigma\)</span></td>
<td>Table 4, Table <span class="math inline">\(4 \times 0.7,\)</span> generic</td>
<td>0.0069</td>
<td>0.0037</td>
<td>42.1</td>
<td>(30211, 2485)</td>
<td>(<span class="math inline">\(10^{5}\)</span>, 77796)</td>
</tr>
<tr class="odd">
<td>uniform</td>
<td>Table 4, Table <span class="math inline">\(4 \times 0.7,\)</span> generic</td>
<td>0.0071</td>
<td>0.0017</td>
<td>1.00</td>
<td>(13043, 689)</td>
<td>(51020, <span class="math inline">\(10^{5}\)</span>)</td>
</tr>
<tr class="even">
<td>uniform, <span class="math inline">\(\varepsilon_\infty\)</span> frozen at 4.86</td>
<td>generic</td>
<td>0.0071</td>
<td>—</td>
<td>4.86</td>
<td>(17629, 1046)</td>
<td>(82313, <span class="math inline">\(10^{5}\)</span>)</td>
</tr>
</tbody>
</table>

</div>
<p>Three starting points give the same answer under each weighting, so the fitter converges; its curves lie within 0.002–0.004 of the Table 4 curve, less than the scatter of the data (median <span class="math inline">\sigma</span> 0.0015, Table 4’s own residual 0.0075); and its residual is lower than Table 4’s. The parameters, however, are not Table 4’s and depend on the weighting, with the second Drude term running to its bounds. A metal’s reflectance near 0.95 fixes the combination of <span class="math inline">\varepsilon_\infty</span> and the two plasma frequencies, not each of them: the problem is degenerate, as the report’s own remark about the second oscillator says. Reproducing Table 4’s <em>numbers</em> would require Irati’s unrecorded choices (where she stopped, what she held). What difes reproduces is the physical content, the curve, and it does so from any start.</p>
<h2 id="c.-the-oxide-film-the-same-bands-a-better-fit" class="anchored">C. The oxide film: the same bands, a better fit</h2>
<p>Table 6 on a frozen Table 4 substrate, incoherent film of 1.095 <span class="math inline">\mu</span>m with the FOCUS form, fitted over 390–1300 <span class="math inline">\mathrm{cm}^{-1}</span> as the report says (118 points):</p>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">weights</th>
<th data-quarto-table-cell-role="th">start</th>
<th data-quarto-table-cell-role="th">rms vs data</th>
<th data-quarto-table-cell-role="th">rms vs curve.dat</th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\varepsilon_\infty\)</span></th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\omega_0\)</span> shifts rms / max</th>
<th data-quarto-table-cell-role="th">within their <span class="math inline">\(\gamma\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td colspan="2">Table 6 as transcribed</td>
<td>0.074</td>
<td>0.026</td>
<td>1.87</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td colspan="2">FOCUS's own curve (curve.dat)</td>
<td>0.046</td>
<td>—</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>measured <span class="math inline">\(\sigma\)</span></td>
<td>Table 6</td>
<td>0.035</td>
<td>0.028</td>
<td>4.0</td>
<td>24 / 60 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></td>
<td>14 of 14</td>
</tr>
<tr class="even">
<td>measured <span class="math inline">\(\sigma\)</span></td>
<td>Table 6, perturbed</td>
<td>0.032</td>
<td>0.028</td>
<td>3.3</td>
<td>27 / 60 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></td>
<td>13 of 14</td>
</tr>
<tr class="odd">
<td>uniform</td>
<td>Table 6</td>
<td>0.031</td>
<td>0.027</td>
<td>3.4</td>
<td>22 / 44 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></td>
<td>13 of 14</td>
</tr>
<tr class="even">
<td>uniform</td>
<td>Table 6, perturbed</td>
<td>0.031</td>
<td>0.027</td>
<td>3.4</td>
<td>22 / 44 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></td>
<td>13 of 14</td>
</tr>
</tbody>
</table>

</div>
<p>Read against FOCUS: FOCUS’s own fitted curve sits 0.046 from the data over the range, and Table 6 as transcribed 0.074 (the missing <span class="math inline">\omega_0</span>, the unknown thickness, and the film form). difes’s refits reach 0.031–0.035, from the report’s values and from a perturbed start alike, and keep thirteen or fourteen of the fourteen oscillators within their own width of the report’s positions. The ones that move are the ones the report flags: the first mode drifts to its bound at 400 <span class="math inline">\mathrm{cm}^{-1}</span> (the edge the report could not fit; a mode below the range), the broad thirteenth at 1127 <span class="math inline">\mathrm{cm}^{-1}</span> with <span class="math inline">\gamma</span> = 495 is replaced by a narrower one, and the last moves to the upper edge. The agreement is where the physics is, in the bands; the disagreement is where the report says its own fit was weak.</p>
<h2 id="d.-the-apps-way" class="anchored">D. The app’s way</h2>
<p>The Bench recipes on the emissivity itself, the sequence a user follows: import the spectrum, set the model, choose Film with the frozen chromium underneath and the FOCUS formula, press Guided fit on 390–1300 <span class="math inline">\mathrm{cm}^{-1}</span>, adopt.</p>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">start</th>
<th data-quarto-table-cell-role="th">strengths → positions → widths → all (rms in E)</th>
<th data-quarto-table-cell-role="th">adopted</th>
<th data-quarto-table-cell-role="th">bands nearest Table 6's 437, 493, 577, 624</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Table 6</td>
<td><span class="math inline">\(0.062 \to 0.032\)</span> <span class="math inline">\(\to 0.032\)</span> <span class="math inline">\(\to 0.032\)</span></td>
<td>14 terms, <span class="math inline">\(\varepsilon_\infty\)</span> 3.3; its R is 0.028 from curve.dat</td>
<td>15, 41, 1, 1 <span class="math inline">\(\mathrm{cm}^{-1}\)</span> away</td>
</tr>
<tr class="even">
<td>the Bench's suggestions</td>
<td><span class="math inline">\(0.111 \to 0.092\)</span> <span class="math inline">\(\to 0.056\)</span> <span class="math inline">\(\to 0.056\)</span></td>
<td>6 terms, <span class="math inline">\(\varepsilon_\infty\)</span> 4.9; its R is 0.037 from curve.dat</td>
<td>15, 21, 63, 111 <span class="math inline">\(\mathrm{cm}^{-1}\)</span> away</td>
</tr>
</tbody>
</table>

</div>
<p>From the report’s values the Bench gives the same result as the fitter in C, in four stages a user can watch. From its own suggestions, found in the fit range, it finds six bands and recovers the two strongest (452 and 514 <span class="math inline">\mathrm{cm}^{-1}</span>) but not the 577 and 624 <span class="math inline">\mathrm{cm}^{-1}</span> pair or the weak overtones above 700 <span class="math inline">\mathrm{cm}^{-1}</span>, which the report needed Larbi’s assignments and a hand-built list of fourteen terms to place; a model of that kind is prior knowledge, and the Bench’s <strong>Import FOCUS model</strong> or the Table 6 example is how it enters.</p>
<h2 id="verdict-for-phase-4" class="anchored">Verdict for phase 4</h2>
<ul>
<li><strong>Exact where it must be.</strong> With the same formula, difes computes FOCUS’s curves to machine precision; the formula FOCUS uses for an incoherent film is now an option, and the difference with the energy-conserving form is documented and visible.</li>
<li><strong>Convergent and consistent.</strong> The fitter reaches the same solution from the report’s values and from generic starts, with lower residuals than the tabulated solutions; its curves agree with FOCUS’s within the data’s scatter.</li>
<li><strong>Parameters agree where the problem is well posed.</strong> The oxide’s band positions, within their widths; chromium’s two Drude terms are degenerate for either program, as the report acknowledges.</li>
<li><strong>Closed on 2 October.</strong> FOCUS’s exported curves agree with difes to the file’s own rounding; level A is a single exact comparison. Which symbol drew the report’s figure 20 remains a curiosity of the report, not of the programs. The effective-medium layer of the later projects is evaluated but not yet fitted in difes.</li>
</ul>
<p>The roadmap’s phase-4 criterion, “the parameters agree within their uncertainties, or the disagreement is understood and written down”, is met in the second sense for chromium and in the first for the oxide’s bands.</p>


<!-- Closes the reading column opened by _gen/docs-nav.html, adds the right
     "On this page" list, and wires: current-page marking in the left nav,
     breadcrumbs, the page TOC (from h2/h3 in the reading column) and a
     scroll-spy. Pure DOM, no library. -->
  </div>
  <aside class="docs-toc"><button class="docs-fold" type="button" data-fold="toc" aria-label="Hide the page outline" title="Hide the page outline">›</button><div class="t">On this page</div><ol></ol></aside>
</div>
<script>
(function () {
  /* 0. The two side panels fold on their chevrons; the choice is remembered in this browser. */
  var docs = document.querySelector('.docs');
  if (docs) {
    var store = {};
    try { store = JSON.parse(localStorage.getItem('docs-fold') || '{}'); } catch (e) { store = {}; }
    function apply() {
      docs.classList.toggle('nav-folded', !!store.nav);
      docs.classList.toggle('toc-folded', !!store.toc);
      document.querySelectorAll('.docs-fold').forEach(function (b) {
        var which = b.getAttribute('data-fold'), folded = !!store[which];
        b.innerHTML = (which === 'nav') === folded ? '&rsaquo;' : '&lsaquo;';
        var what = which === 'nav' ? 'the navigation' : 'the page outline';
        b.title = (folded ? 'Show ' : 'Hide ') + what; b.setAttribute('aria-label', b.title);
      });
    }
    document.querySelectorAll('.docs-fold').forEach(function (b) {
      b.addEventListener('click', function () {
        var which = b.getAttribute('data-fold'); store[which] = !store[which];
        try { localStorage.setItem('docs-fold', JSON.stringify(store)); } catch (e) {}
        apply();
      });
    });
    apply();
  }
  /* 0b. The header ribbon: mark the entry whose section holds this page. Quarto rewrites the hrefs to
     relative paths, so folders are read from the resolved URLs; the Overview link gives the site root. */
  (function () {
    var links = Array.prototype.slice.call(document.querySelectorAll('.site-nav a'));
    if (!links.length) return;
    function folder(path) { var s = path.split('/').filter(Boolean); return s.length > 1 ? s[s.length - 2] : ''; }
    var wm = document.querySelector('a.wordmark');            // the wordmark links to the site root
    var root = folder((wm || links[0]).pathname);
    var map = { 'focus-literature': 'validation', user: 'manual', theory: 'manual' };
    function key(path) { var f = folder(path); if (f === root) return 'overview'; return map[f] || f; }
    var here = key(location.pathname);
    links.forEach(function (a) { a.classList.toggle('current', key(a.pathname) === here); });
  })();

  var main = document.querySelector('.docs-main');
  var nav = document.querySelector('.docs-nav');
  var toc = document.querySelector('.docs-toc ol');
  if (!main || !nav || !toc) return;

  /* 1. Left nav: mark the current page (and section, if the hash matches). */
  var here = location.pathname.replace(/\/index\.html$/, '/');
  var links = Array.prototype.slice.call(nav.querySelectorAll('a'));
  var pageLink = null, hashLink = null;
  links.forEach(function (a) {
    var p = a.pathname.replace(/\/index\.html$/, '/');
    if (p !== here) return;
    if (!a.hash && !pageLink) pageLink = a;
    if (a.hash && a.hash === location.hash) hashLink = a;
  });
  var cur = hashLink || pageLink;
  if (cur) {
    cur.classList.add('current');
    var det = cur.closest('details.group');
    if (det) { det.open = true; det.classList.add('has-current'); }
    /* Breadcrumbs: group title › page (› section). */
    var crumbs = document.createElement('div');
    crumbs.className = 'docs-crumbs';
    var g = det ? det.querySelector('summary.t') : null;
    var parts = [];
    function push(t) { if (t && parts[parts.length - 1] !== t) parts.push(t); }
    if (g) push(g.textContent.trim());
    if (pageLink && pageLink !== cur) push(pageLink.textContent.trim());
    push(cur.textContent.trim());
    crumbs.innerHTML = parts.map(function (t, i) {
      return (i ? '<span class="sep">›</span>' : '') + '<span>' + t.replace(/</g, '&lt;') + '</span>';
    }).join('');
    main.insertBefore(crumbs, main.firstChild);
  }

  /* 2. Right "On this page": h2 and h3 of the reading column. */
  var used = {};
  var heads = Array.prototype.slice.call(main.querySelectorAll('h2, h3')).filter(function (h) {
    if (h.closest('.site-foot, .featured-band, .msg-grid, [data-toc="no"]')) return false;
    if (h.classList.contains('unnumbered') || h.id === 'contenido') return false;
    return h.textContent.trim().length > 0;
  });
  heads.forEach(function (h) {
    if (!h.id) {
      var s = h.textContent.trim().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
        .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'sec';
      while (used[s] || document.getElementById(s)) s += '-';
      h.id = s;
    }
    used[h.id] = true;
    var li = document.createElement('li');
    if (h.tagName === 'H3') li.className = 'l3';
    var a = document.createElement('a');
    a.href = '#' + h.id;
    /* This runs before KaTeX has rendered the headings, so a heading with mathematics still holds TeX
       source: copy its markup, including the math spans, and let the page's KaTeX pass render the copy. */
    var copy = h.cloneNode(true);
    copy.querySelectorAll('.katex-mathml, annotation, .anchorjs-link').forEach(function (n) { n.remove(); });
    var label = copy.textContent.trim().replace(/\s+/g, ' ');
    if (copy.querySelector('.math, .math-done, .katex')) a.innerHTML = copy.innerHTML.trim();
    else a.textContent = label.length > 72 ? label.slice(0, 70).replace(/[\s,;:]+\S*$/, '') + '…' : label;
    a.title = label;
    li.appendChild(a);
    toc.appendChild(li);
  });
  if (!heads.length) { document.querySelector('.docs-toc').hidden = true; return; }

  /* 3. Scroll-spy. */
  var items = Array.prototype.slice.call(toc.querySelectorAll('a'));
  function spy() {
    var y = window.scrollY + 120, best = null;
    heads.forEach(function (h) { if (h.getBoundingClientRect().top + window.scrollY <= y) best = h; });
    items.forEach(function (a) { a.classList.toggle('current', best && a.getAttribute('href') === '#' + best.id); });
  }
  window.addEventListener('scroll', spy, { passive: true });
  window.addEventListener('hashchange', spy);
  spy();
})();
</script>
<footer class="site-foot">
  <div class="site-foot__inner">
    <div class="foot-grid">
      <div class="foot-about">
        <h4 class="anchored">What this is</h4>
        <p>The test ledger of difes, a program for dielectric-function models, reflectivity, emissivity, Kramers–Kronig and fitting of infrared spectra, built as a personal project to give the group an open and documented counterpart of FOCUS. Every check the program has passed through is listed here with its grade, its data and its result, next to the validation pages the checks come from and the complete manual: how the app looks and works, and the physics it implements, equation by equation.</p>
        <div class="cite-block">Josu M. Igartua · Departamento de Física, UPV/EHU<br>josu.igartua@ehu.eus</div>
      </div>
      <div><h4 class="anchored">This site</h4><ul>
        <li><a href="../tests/index.html">The test ledger</a></li><li><a href="../validation/index.html">Against FOCUS</a></li><li><a href="../validation/irati-path.html">Irati's path</a></li><li><a href="../validation/papers.html">Published works</a></li><li><a href="../validation/focus-samples.html">FOCUS's sample projects</a></li><li><a href="../validation/literature.html">The literature</a></li><li><a href="../manual/index.html">The manual: using difes</a></li><li><a href="../manual/theory/index.html">The manual: theoretical basis</a></li></ul></div>
      <div><h4 class="anchored">Sources</h4><ul>
        <li><a href="https://doi.org/10.1366/000370207783292163">De Sousa Meneses et al. 2007 (CFRC)</a></li>
        <li><a href="https://doi.org/10.1366/0003702041655467">De Sousa Meneses et al. 2004 (semi-quantum models)</a></li>
        <li><a href="https://doi.org/10.1063/1.1979470">Kuzmenko 2005 (RefFIT, VDF)</a></li>
        <li><a href="https://www.cemhti.cnrs-orleans.fr/pot/software/focus.html">FOCUS at CEMHTI</a></li></ul></div>
      <div><h4 class="anchored">Status</h4><ul>
        <li>A twin of the project site, which is not published yet; the greyed references point to pages of that site</li>
        <li>Regenerated from the same sources on every render</li></ul></div>
    </div>
    <div class="foot-bottom">
      <span>© 2026 Josu M. Igartua</span>
      <span>Quarto · family design kit</span>
    </div>
  </div>
</footer>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>