<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta name="robots" content="noindex, nofollow">

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Published works, solved again · difes test ledger – difes · the test ledger</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-afe927e19676d0e50b1726048be49fb1.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700&amp;family=Source+Sans+3:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=IBM+Plex+Mono:wght@400;500&amp;display=swap" rel="stylesheet">
<!-- KaTeX auto-render: publication titles carry TeX inside generated HTML that
     Quarto's own math pipeline never sees (same approach as thermomat). -->
<script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
<script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script>
<script defer="" src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"></script>
<script>
/* The header ribbon is sticky; the side columns and anchor targets need its height. */
(function () {
  function headH() {
    var t = document.querySelector(".topline"), h = document.querySelector(".site-head");
    var px = (t ? t.offsetHeight : 0) + (h ? h.offsetHeight : 0);
    if (px) document.documentElement.style.setProperty("--head-h", px + "px");
  }
  document.addEventListener("DOMContentLoaded", headH);
  window.addEventListener("load", headH);
  window.addEventListener("resize", headH);
})();
document.addEventListener("DOMContentLoaded", function () {
  if (window.renderMathInElement) {
    renderMathInElement(document.body, {
      delimiters: [{ left: "$$", right: "$$", display: true }, { left: "$", right: "$", display: false }, { left: "\\(", right: "\\)", display: false }],
      throwOnError: false
    });
  }
  /* Quarto's KaTeX pipeline writes <span class="math inline">TeX</span> without delimiters and renders
     them in a loop that reads firstChild.data; that loop dies at the first span the auto-render above
     has already turned into KaTeX markup, leaving every later formula raw. Render the rest here. */
  if (window.katex) {
    document.querySelectorAll(".math").forEach(function (el) {
      if (!el.querySelector(".katex")) {
        var t = el.textContent.replace(/^\s*\\[\(\[]/, "").replace(/\\[\)\]]\s*$/, "");
        try { katex.render(t, el, { displayMode: el.classList.contains("display"), throwOnError: false }); } catch (e) {}
      }
      /* Quarto's loop would still visit this span and wipe it (firstChild is now an element, not text):
         take it out of its sight. No stylesheet of the site depends on the class; KaTeX's own output carries the layout. */
      el.classList.remove("math"); el.classList.add("math-done");
    });
  }
});
</script>

  <script defer="" src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/styles/theme.css">
<link rel="stylesheet" href="../assets/styles/site.css">
<link rel="stylesheet" href="../assets/styles/twin.css">
</head>

<body>

<!-- Header of the twin site: the test ledger published on its own. The entries are the groups of
     data/nav-twin.yml, in the same order. -->
<div class="topline"></div>
<header class="site-head">
  <div class="site-head__inner">
    <a href="../index.html" class="wordmark">difes <span class="accent">test</span> ledger
      <span class="wordmark-sub">Every check of the program, graded, with the validation pages and the manual · a twin of the project site, regenerated with it</span>
    </a>
    <nav class="site-nav">
      <a href="../tests/index.html">Ledger</a>
      <a href="../validation/index.html">Validation</a>
      <a href="../manual/index.html">Manual</a>
      <span class="nav-right">
        <a href="../assets/documents/test-ledger.pdf" class="nav-dl">Ledger as PDF</a>
      </span>
    </nav>
  </div>
</header>
<!-- generated by tools/build.py: left navigation + opening of the reading column -->
<div class="docs">
<nav class="docs-nav" aria-label="Site sections">
<button class="docs-fold" type="button" data-fold="nav" aria-label="Hide the navigation" title="Hide the navigation">‹</button>
<details class="group" open=""><summary class="t">Ledger</summary><ul><li><a href="../tests/index.html">The test ledger, difes's presentation card</a></li></ul></details>
<details class="group" open=""><summary class="t">Validation</summary><ul><li><a href="../validation/index.html">Against FOCUS, on Irati's data</a></li><li><a href="../validation/irati-path.html">Irati's path, step by step</a></li><li><a href="../validation/papers.html">Published works, solved again</a></li><li><a href="../validation/focus-samples.html">FOCUS's own sample projects</a></li><li><a href="../validation/literature.html">The FOCUS literature, reproduced</a></li></ul></details>
<details class="group" open=""><summary class="t">Manual</summary><div class="sub"><div class="st">Using difes</div><ul><li><a href="../manual/index.html">About the manual</a></li><li><a href="../manual/user/getting-started.html">Getting started</a></li><li><a href="../manual/user/spectra-models.html">Spectra and models</a></li><li><a href="../manual/user/simulate-fit.html">Simulating and fitting</a></li><li><a href="../manual/user/kramers-kronig.html">Kramers–Kronig and CFRC</a></li><li><a href="../manual/user/language-sessions.html">Formulas, sessions, views, libraries</a></li><li><a href="../manual/user/focus-exchange.html">Exchanging with FOCUS</a></li><li><a href="../manual/user/reffit.html">Exchanging with RefFIT</a></li><li><a href="../manual/user/shell.html">The shell</a></li><li><a href="../manual/user/bench.html">The Bench</a></li><li><a href="../manual/user/digitise.html">Digitising figures</a></li><li><a href="../manual/user/api.html">Python reference</a></li></ul></div><div class="sub"><div class="st">Theoretical basis</div><ul><li><a href="../manual/theory/index.html">Scope and conventions</a></li><li><a href="../manual/theory/response.html">The dielectric response</a></li><li><a href="../manual/theory/models.html">Models of the dielectric function</a></li><li><a href="../manual/theory/optics.html">From $\varepsilon$ to the measured spectrum</a></li><li><a href="../manual/theory/kramers-kronig.html">Kramers–Kronig on a finite range</a></li><li><a href="../manual/theory/fitting.html">Least-squares fitting</a></li><li><a href="../manual/theory/instrument.html">The measurement</a></li><li><a href="../manual/theory/references.html">References</a></li></ul></div></details>
<details class="group" open=""><summary class="t">Documents</summary><ul><li><a href="../assets/documents/test-ledger.pdf">The test ledger (PDF)</a></li><li><a href="../assets/documents/validation-focus.pdf">difes against FOCUS, for Irati (PDF)</a></li></ul></details>
</nav>
<div class="docs-main">

<header id="title-block-header">
<h1 class="title">Published works, solved again</h1>
<p class="subtitle">Two analyses done with FOCUS and printed in the literature, redone in difes from their tables and figures. Where the paper printed everything, difes reproduces it without a fit; where it did not, difes’s fit meets FOCUS’s curve within the digitisation.</p>

</header>


<p class="lede">Josu's proposal of 2 October: beyond Irati's data, check difes against published work that used FOCUS, digitising the figures where no data files exist. Two works were chosen for being complete on paper and different in model: a four-parameter anisotropic emissivity from the group's own circle, and FOCUS's Gaussian self-energy on the fluorides. The scripts and the extracted data are in <code>difes/examples/papers/</code>; the sessions are under Examples in the app ("Paper · …").</p>
<h2 id="reading-figures" class="anchored">Reading figures</h2>
<p>Two extractors were written for this. For a <strong>bitmap</strong> figure, <code>digitize.py</code> finds the plot frame, calibrates the axes from the known ranges, masks one colour, reads one point per column for a line or the centroids of blobs for markers, excludes the legend, converts wavelength to wavenumber, and writes an overlay image to check by eye; on a 900‑pixel figure it is good to about <span class="math inline">5\times10^{-3}</span> of the axis span. For a <strong>vector</strong> figure in a PDF, <code>vectorize.py</code> reads the plotted polylines themselves with PyMuPDF and calibrates the axes on the positions of the tick labels, so a rotated page or an inset is no obstacle; the precision is that of the authors’ plotting.</p>
<h2 id="pyrolytic-boron-nitride-gonzález-de-arrieta-et-al.-2017" class="anchored">1 · Pyrolytic boron nitride, González de Arrieta et al.&nbsp;(2017)</h2>
<p><em>I. González de Arrieta, T. Echániz, R. Fuente, L. del Campo, D. De Sousa Meneses, G. A. López, M. J. Tello, J. Quant. Spectrosc. Radiat. Transfer 194 (2017) 1–6.</em> Emissivity of pBN between 390 and 1050 °C, 4–16 <span class="math inline">\mu</span>m, fitted with FOCUS: two Kurosawa modes (<span class="math inline">\perp</span> and <span class="math inline">\parallel</span> to the c axis), the random‑orientation average <span class="math inline">\varepsilon_{av} = \tfrac{1}{3}\varepsilon_\parallel + \tfrac{2}{3}\varepsilon_\perp</span>, and a Maxwell–Garnett correction for carbon inclusions (<span class="math inline">\varepsilon_i = 5</span>, <span class="math inline">f = 8\,\%</span>). Table 1 prints the frequencies and dielectric constants at 392 °C; the dampings only for the perpendicular mode. Fig. 2 shows the spectra at 392, 691 and 1043 °C; Fig. 3 the data and FOCUS’s fit at 691 °C. All were digitised.</p>
<figure>
<img src="../assets/figures/paper_pbn.png" alt="pBN: Table 1 forward and refit at 392 °C; the 691 °C data with FOCUS's fit and difes's; the two fits against each other" style="width:100%; border:1px solid var(--line, #ddd);">
<figcaption>Left: the 392 °C spectrum with Table 1 forward (dashed) and difes's refit (dotted). Middle: the 691 °C data of Fig. 3 with FOCUS's fitted curve (grey) and difes's fits from Table 1 and from a generic start. Right: difes's fit minus FOCUS's, against the digitisation precision.</figcaption>
</figure>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">test</th>
<th data-quarto-table-cell-role="th">result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Table 1 forward at 392 °C (the two parallel dampings fitted, as they are not printed)</td>
<td>rms 0.041 against the digitised spectrum. Above 2300 <span class="math inline">\(\mathrm{cm}^{-1}\)</span> the table gives <span class="math inline">\(E = 0.90\)</span> where the spectrum reads 0.94, and the band edge sits 50 <span class="math inline">\(\mathrm{cm}^{-1}\)</span> too low: <strong>the table as printed does not regenerate the figure</strong>.</td>
</tr>
<tr class="even">
<td>refit at 392 °C, all ten parameters free</td>
<td>rms 0.016; <span class="math inline">\(\varepsilon_{\infty\perp}\)</span> <span class="math inline">\(5.19 \to 3.89,\)</span> <span class="math inline">\(\Omega_{LO\perp}\)</span> <span class="math inline">\(1601 \to 1664,\)</span> <span class="math inline">\(\Omega_{LO\parallel}\)</span> <span class="math inline">\(829 \to 891,\)</span> the TO frequencies within 3 <span class="math inline">\(\mathrm{cm}^{-1}\)</span> of the table</td>
</tr>
<tr class="odd">
<td>fit at 691 °C of the digitised data of Fig. 3</td>
<td>rms 0.014 against the points; FOCUS's own curve sits 0.015 from the same points; <strong>difes's curve and FOCUS's agree to rms 0.0055</strong>, the digitisation precision</td>
</tr>
<tr class="even">
<td>the same from a generic start (frequencies −5 %, dampings 50)</td>
<td>the same curve (rms 0.014); frequencies and dielectric constants within a few percent of the fit from Table 1, the LO frequencies the least determined</td>
</tr>
</tbody>
</table>

</div>
<p>The lesson is the one the chromium gave: the <em>curves</em> agree between the two programs to the precision of the data, here the precision of a digitised figure; the <em>parameters</em> are what the model lets them be. That Table 1 does not reproduce Fig. 2 is a finding about the table (a transcription, a different <span class="math inline">\varepsilon_\infty</span> convention, or values from another fit) that the authors, who are colleagues, can settle; their raw spectra would also replace the digitisation.</p>
<p><strong>The TFM behind the paper (4 October 2026).</strong> The first author’s master’s thesis (UPV/EHU, 2016) holds the same work with more of it printed: Table 4.2 gives the Kurosawa parameters at eight temperatures (the paper’s Table 1 is its 392 °C column), and Fig. 4.11 draws the model’s own <span class="math inline">\varepsilon'</span> and <span class="math inline">\varepsilon''</span> at 691 °C next to a Kramers–Kronig inversion of the measured reflectivity, which the paper does not show. That figure is the model as the fitting program computed it, so it tests the table directly, on <span class="math inline">\varepsilon</span> rather than on emissivity (<code>examples/papers/pbn2017/tfm_inigo.py</code>, axes calibrated on the tick marks).</p>
<figure>
<img src="../assets/figures/pbn_tfm_eps.png" alt="pBN at 691 °C: the model dielectric function drawn in the TFM against Table 4.2 in difes and against difes's refit of the paper's data" style="width:100%; border:1px solid var(--line, #ddd);">
<figcaption>The model <span class="math inline">\(\varepsilon'\)</span> and <span class="math inline">\(\varepsilon''\)</span> drawn in the TFM at 691 °C (black), Table 4.2's 691 °C column evaluated in difes (dashed) and difes's refit of the paper's 691 °C emissivity (dotted).</figcaption>
</figure>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">drawn in the TFM</th>
<th data-quarto-table-cell-role="th">Table 4.2 in difes</th>
<th data-quarto-table-cell-role="th">difes refit of the paper's data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\varepsilon'\)</span> at 4–5 <span class="math inline">\(\mu\)</span>m</td>
<td>2.76</td>
<td>3.39</td>
<td>2.70</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\varepsilon'\)</span> maximum</td>
<td>22.9</td>
<td>24.4</td>
<td>22.7</td>
</tr>
<tr class="odd">
<td>rms of <span class="math inline">\(\varepsilon'\)</span> over 4–16 <span class="math inline">\(\mu\)</span>m</td>
<td>—</td>
<td>0.90</td>
<td>0.63</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\varepsilon_{\infty\perp}\)</span></td>
<td>3.89 reproduces the drawn level with the table's other values</td>
<td>5.18</td>
<td>4.10</td>
</tr>
</tbody>
</table>

</div>
<p>The dielectric function the thesis drew is the one difes’s refit finds, not the one its table gives: the printed <span class="math inline">\varepsilon_{\infty\perp}</span> is not the value of the plotted model, in the thesis as in the paper, while the TO frequencies agree in all three. This narrows the question for the author to one number and its convention. The same thesis also records, in its Table 4.3, a double-damping Drude fit of a cBN/TiCN composite at eight temperatures, a model difes has as <code>extdrude</code>; and the author’s earlier TFG (2015) fitted a cBN cutting tool with RefFIT rather than FOCUS, Drude plus Lorentz, with full parameter tables.</p>
<p><strong>The PhD thesis (4 October 2026).</strong> The same author’s doctoral thesis (UPV/EHU, 2020) uses FOCUS in three places, none with a parameter table: a causal-Voigt fit of the loss function of alumina around its 932 <span class="math inline">\mathrm{cm}^{-1}</span> LO mode (inset of Fig. 4.7, only the frequency is quoted); the generalised Drude–Lorentz fit of the thesis’s eq. 2.38 to the normal spectral emittance of a Pyromark coating at 1073 K (Fig. 4.14), which the text itself calls semi-quantitative; and Drude fits (eq. 2.34) to four vanadium alloys at 973 K (Fig. 5.9), whose results are shown only as a chart of <span class="math inline">\sigma = \omega_p^2/4\pi\gamma</span> and <span class="math inline">\varepsilon_\infty</span> (Fig. 5.10). The figures are vector drawings, so the measured points and FOCUS’s fitted curves are read from the PDF paths exactly, without pixel digitising (<code>examples/papers/inigo_thesis/thesis_fits.py</code>). difes then fits the same model to the same data from a generic start, and the question is whether it lands on FOCUS’s curve.</p>
<figure>
<img src="../assets/figures/inigo_thesis_fits.png" alt="Iñigo's thesis: Pyromark generalised Drude–Lorentz and vanadium Drude fits, FOCUS's curves against difes's refits" style="width:100%; border:1px solid var(--line, #ddd);">
<figcaption>Left: Pyromark at 1073 K, the measured points and FOCUS's fit from Fig. 4.14, and difes's fit of the same eight-parameter model (dashed). Right: the four vanadium alloys at 973 K from Fig. 5.9, FOCUS's Drude curves in colour and difes's Drude fits dashed on top of them.</figcaption>
</figure>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">sample, 973 K</th>
<th data-quarto-table-cell-role="th">difes vs FOCUS's curve, rms</th>
<th data-quarto-table-cell-role="th">max</th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\varepsilon_\infty\)</span></th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\omega_p\)</span> (<span class="math inline">\(\mathrm{cm}^{-1}\)</span>)</th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\gamma\)</span> (<span class="math inline">\(\mathrm{cm}^{-1}\)</span>)</th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\sigma=\omega_p^2/4\pi\gamma\)</span> (<span class="math inline">\(\mathrm{cm}^{-1}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>EBM</td>
<td>0.0007</td>
<td>0.0014</td>
<td>376</td>
<td>72 850</td>
<td>5 500</td>
<td>76 800</td>
</tr>
<tr class="even">
<td>EBM-HT</td>
<td>0.0008</td>
<td>0.0011</td>
<td>33</td>
<td>42 540</td>
<td>3 680</td>
<td>39 100</td>
</tr>
<tr class="odd">
<td>MA</td>
<td>0.0005</td>
<td>0.0007</td>
<td>225</td>
<td>98 600</td>
<td>12 170</td>
<td>63 600</td>
</tr>
<tr class="even">
<td>MA-HT</td>
<td>0.0006</td>
<td>0.0015</td>
<td>252</td>
<td>61 000</td>
<td>5 960</td>
<td>49 700</td>
</tr>
</tbody>
</table>

</div>
<p>The vanadium case is clean: for all four alloys difes’s Drude fit falls on FOCUS’s drawn curve to better than 0.001 in emissivity, the line width of the figure, and the conductivities it implies sit within the 0 to 80 000 <span class="math inline">\mathrm{cm}^{-1}</span> axis of the thesis’s Fig. 5.10. The <span class="math inline">\varepsilon_\infty</span> values are large and poorly determined, as a Drude term’s <span class="math inline">\varepsilon_\infty</span> is when only emissivity below 3100 <span class="math inline">\mathrm{cm}^{-1}</span> constrains it; FOCUS’s drawn curves carry no more information about them than difes’s fits do, and the thesis itself discusses them as effective values.</p>
<p>The Pyromark case is the first one in this programme where difes and FOCUS, given the same model and the same data, end in different places, and it is instructive. difes’s fit has rms 0.0086 against the measured points; FOCUS’s drawn curve has 0.0130 against the same points, and the two curves differ by 0.0094 rms, 0.022 at most. Fitting the same eight-parameter model to FOCUS’s drawn curve instead of to the data reproduces that curve to 0.0004, so FOCUS’s result is a genuine member of the model family and difes evaluates the model as FOCUS does; the two programs simply stopped in different minima of a shallow problem, the oscillator at 1060 <span class="math inline">\mathrm{cm}^{-1}</span> with a width of 105 <span class="math inline">\mathrm{cm}^{-1}</span> and a heavily overdamped Drude term in FOCUS’s solution against a wide oscillator at 1083 <span class="math inline">\mathrm{cm}^{-1}</span> and a narrow Drude term in difes’s. On a fit its author describes as semi-quantitative, with eight free parameters and a single smooth spectrum, the better residual is difes’s, and the difference is a statement about the problem, not about either program’s optics.</p>
<h2 id="mathrmcaf_2-and-mathrmbaf_2-passerat-de-silans-et-al.-2009" class="anchored">2 · <span class="math inline">\mathrm{CaF_{2}}</span> and <span class="math inline">\mathrm{BaF_{2}}</span>, Passerat de Silans et al.&nbsp;(2009)</h2>
<p><em>T. Passerat de Silans, I. Maurin, P. Chaves de Souza Segundo, S. Saltiel, M.-P. Gorza, M. Ducloy, D. Bloch, D. De Sousa Meneses, P. Echegut, arXiv:0905.4710 (2009).</em> Reflectivity of <span class="math inline">\mathrm{CaF_{2}}</span>, <span class="math inline">\mathrm{BaF_{2}}</span> and sapphire from 22 to 500 °C, fitted with FOCUS: one phonon whose damping is a self‑energy of Gaussian bands with their Kramers–Kronig partners (the paper’s eqs. 3–4, FOCUS’s anharmonic phonon). Tables I and II print every parameter at six temperatures; Figs. 1 and 2 are vector graphics, so the measured curves were read exactly. In difes the model is one expression: <code>phonon_anharmonic(x, S, Ω, −2Ω·Σ gaussian_kkg(x, Aₙ, ω₀ₙ, γₙ))</code> on top of <span class="math inline">\varepsilon_\infty</span>.</p>
<figure>
<img src="../assets/figures/paper_fluorides.png" alt="CaF2 and BaF2: the paper's data and its tables computed by difes, at six temperatures, with residuals" style="width:100%; border:1px solid var(--line, #ddd);">
<figcaption>The paper's measured curves (solid) and the paper's tables computed by difes (dashed) for <span class="math inline">\(\mathrm{CaF_{2}}\)</span> and <span class="math inline">\(\mathrm{BaF_{2}}\)</span> at 22, 100, 200, 300, 400 and 500 °C; right, the differences. No parameter was fitted.</figcaption>
</figure>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">T (°C)</th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\mathrm{CaF_{2}}\)</span> · rms, 0–1000 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\mathrm{CaF_{2}}\)</span> · band 100–700</th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\mathrm{BaF_{2}}\)</span> · rms, 0–1000 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></th>
<th data-quarto-table-cell-role="th"><span class="math inline">\(\mathrm{BaF_{2}}\)</span> · band 100–700</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>22</td>
<td>0.0078</td>
<td>0.0040</td>
<td>0.0088</td>
<td>0.0053</td>
</tr>
<tr class="even">
<td>100</td>
<td>0.0042</td>
<td>0.0042</td>
<td>0.0095</td>
<td>0.0044</td>
</tr>
<tr class="odd">
<td>200</td>
<td>0.0057</td>
<td>0.0055</td>
<td>0.0087</td>
<td>0.0041</td>
</tr>
<tr class="even">
<td>300</td>
<td>0.0078</td>
<td>0.0078</td>
<td>0.0077</td>
<td>0.0044</td>
</tr>
<tr class="odd">
<td>400</td>
<td>0.0082</td>
<td>0.0078</td>
<td>0.0076</td>
<td>0.0058</td>
</tr>
<tr class="even">
<td>500</td>
<td>0.0133</td>
<td>0.0130</td>
<td>0.0071</td>
<td>0.0051</td>
</tr>
</tbody>
</table>

</div>
<p>The paper states a measurement accuracy of 2–3 % and its fits lie on the data in the figures; difes, computing the paper’s numbers, lands on the data to 0.4–1.3 %, every dielectric function passive. A refit at 22 °C with everything free moves the curve by less than the measurement noise (<span class="math inline">\varepsilon_\infty</span> <span class="math inline">2.02 \to 2.03</span> for <span class="math inline">\mathrm{CaF_{2}}</span>, <span class="math inline">2.12 \to 2.22</span> for <span class="math inline">\mathrm{BaF_{2}}</span>), so the printed parameters are a minimum for difes as they were for FOCUS. This settles that difes’s Gaussian self‑energy is FOCUS’s, on the material FOCUS’s authors chose to show it on.</p>
<h2 id="sapphire-the-same-paper-table-iii" class="anchored">3 · Sapphire, the same paper, Table III</h2>
<p>The third case the previous page announced. <span class="math inline">\mathrm{Al_{2}O_{3}}</span> with the electric field perpendicular to the c axis, 22 to 500 °C, four phonons, each with its own Gaussian self‑energy (one Gaussian for phonons 1, 2 and 4, four for phonon 3): 41 parameters per temperature, all printed. The six measured curves of Fig. 3 are drawn as a single black path in the PDF; the extractor cuts it where the wavenumber jumps back and names the pieces by their band maximum, which decreases with temperature.</p>
<figure>
<img src="../assets/figures/paper_sapphire.png" alt="Sapphire: the paper's data and Table III computed by difes at six temperatures, the residuals, and the dielectric function" style="width:100%; border:1px solid var(--line, #ddd);">
<figcaption>Left: the measured reflectivity (solid) and Table III in difes (dashed) at six temperatures; middle: the differences; right: the dielectric function of the table at 22 °C, with its four modes.</figcaption>
</figure>
<div class="table-wrap">

<table class="caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">T (°C)</th>
<th data-quarto-table-cell-role="th">22</th>
<th data-quarto-table-cell-role="th">100</th>
<th data-quarto-table-cell-role="th">200</th>
<th data-quarto-table-cell-role="th">300</th>
<th data-quarto-table-cell-role="th">400</th>
<th data-quarto-table-cell-role="th">500</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rms, 0–2000 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></td>
<td>0.0138</td>
<td>0.0101</td>
<td>0.0084</td>
<td>0.0067</td>
<td>0.0062</td>
<td>0.0061</td>
</tr>
<tr class="even">
<td>rms, 300–1000 <span class="math inline">\(\mathrm{cm}^{-1}\)</span></td>
<td>0.0083</td>
<td>0.0121</td>
<td>0.0093</td>
<td>0.0071</td>
<td>0.0067</td>
<td>0.0069</td>
</tr>
<tr class="odd">
<td>band maximum, model / data</td>
<td>0.975 / 0.986</td>
<td>0.954 / 0.953</td>
<td>0.930 / 0.928</td>
<td>0.904 / 0.904</td>
<td>0.875 / 0.876</td>
<td>0.853 / 0.857</td>
</tr>
</tbody>
</table>

</div>
<p>The four‑phonon model with Gaussian self‑energies reproduces the measured reflectivity to 0.6–1.4 % at every temperature, every dielectric function passive; the largest difference is at 22 °C on the sharp 440 <span class="math inline">\mathrm{cm}^{-1}</span> peak, where the drawn curve reaches 0.986 and the table 0.975, a sharpness the plot’s own resolution limits. A refit of the strengths, frequencies and <span class="math inline">(_)</span> at 22 °C moves the frequencies by less than 1 % and the rms from 0.0138 to 0.0131: the printed values are a minimum for difes too.</p>
<h2 id="what-these-three-add-to-the-validation" class="anchored">What these three add to the validation</h2>
<ul>
<li><strong>Breadth of model.</strong> Chromium tested Drude and Lorentz terms and films; the boron nitride tests the four‑parameter model, an anisotropic average and an effective medium; the fluorides and the sapphire test the Gaussian self‑energy with one and with four phonons. Every model family FOCUS’s help documents has now been computed against something FOCUS produced.</li>
<li><strong>A method.</strong> Any paper with a parameter table and a figure can be redone in an afternoon: vector figures exactly, bitmaps to half a percent. The two scripts are the start of a <em>Digitise</em> panel for the app.</li>
<li><strong>Next.</strong> The boron nitride table deserves a question to its authors; and the extractors deserve a place in the app, as a Digitise panel.</li>
</ul>


<!-- Closes the reading column opened by _gen/docs-nav.html, adds the right
     "On this page" list, and wires: current-page marking in the left nav,
     breadcrumbs, the page TOC (from h2/h3 in the reading column) and a
     scroll-spy. Pure DOM, no library. -->
  </div>
  <aside class="docs-toc"><button class="docs-fold" type="button" data-fold="toc" aria-label="Hide the page outline" title="Hide the page outline">›</button><div class="t">On this page</div><ol></ol></aside>
</div>
<script>
(function () {
  /* 0. The two side panels fold on their chevrons; the choice is remembered in this browser. */
  var docs = document.querySelector('.docs');
  if (docs) {
    var store = {};
    try { store = JSON.parse(localStorage.getItem('docs-fold') || '{}'); } catch (e) { store = {}; }
    function apply() {
      docs.classList.toggle('nav-folded', !!store.nav);
      docs.classList.toggle('toc-folded', !!store.toc);
      document.querySelectorAll('.docs-fold').forEach(function (b) {
        var which = b.getAttribute('data-fold'), folded = !!store[which];
        b.innerHTML = (which === 'nav') === folded ? '&rsaquo;' : '&lsaquo;';
        var what = which === 'nav' ? 'the navigation' : 'the page outline';
        b.title = (folded ? 'Show ' : 'Hide ') + what; b.setAttribute('aria-label', b.title);
      });
    }
    document.querySelectorAll('.docs-fold').forEach(function (b) {
      b.addEventListener('click', function () {
        var which = b.getAttribute('data-fold'); store[which] = !store[which];
        try { localStorage.setItem('docs-fold', JSON.stringify(store)); } catch (e) {}
        apply();
      });
    });
    apply();
  }
  /* 0b. The header ribbon: mark the entry whose section holds this page. Quarto rewrites the hrefs to
     relative paths, so folders are read from the resolved URLs; the Overview link gives the site root. */
  (function () {
    var links = Array.prototype.slice.call(document.querySelectorAll('.site-nav a'));
    if (!links.length) return;
    function folder(path) { var s = path.split('/').filter(Boolean); return s.length > 1 ? s[s.length - 2] : ''; }
    var wm = document.querySelector('a.wordmark');            // the wordmark links to the site root
    var root = folder((wm || links[0]).pathname);
    var map = { 'focus-literature': 'validation', user: 'manual', theory: 'manual' };
    function key(path) { var f = folder(path); if (f === root) return 'overview'; return map[f] || f; }
    var here = key(location.pathname);
    links.forEach(function (a) { a.classList.toggle('current', key(a.pathname) === here); });
  })();

  var main = document.querySelector('.docs-main');
  var nav = document.querySelector('.docs-nav');
  var toc = document.querySelector('.docs-toc ol');
  if (!main || !nav || !toc) return;

  /* 1. Left nav: mark the current page (and section, if the hash matches). */
  var here = location.pathname.replace(/\/index\.html$/, '/');
  var links = Array.prototype.slice.call(nav.querySelectorAll('a'));
  var pageLink = null, hashLink = null;
  links.forEach(function (a) {
    var p = a.pathname.replace(/\/index\.html$/, '/');
    if (p !== here) return;
    if (!a.hash && !pageLink) pageLink = a;
    if (a.hash && a.hash === location.hash) hashLink = a;
  });
  var cur = hashLink || pageLink;
  if (cur) {
    cur.classList.add('current');
    var det = cur.closest('details.group');
    if (det) { det.open = true; det.classList.add('has-current'); }
    /* Breadcrumbs: group title › page (› section). */
    var crumbs = document.createElement('div');
    crumbs.className = 'docs-crumbs';
    var g = det ? det.querySelector('summary.t') : null;
    var parts = [];
    function push(t) { if (t && parts[parts.length - 1] !== t) parts.push(t); }
    if (g) push(g.textContent.trim());
    if (pageLink && pageLink !== cur) push(pageLink.textContent.trim());
    push(cur.textContent.trim());
    crumbs.innerHTML = parts.map(function (t, i) {
      return (i ? '<span class="sep">›</span>' : '') + '<span>' + t.replace(/</g, '&lt;') + '</span>';
    }).join('');
    main.insertBefore(crumbs, main.firstChild);
  }

  /* 2. Right "On this page": h2 and h3 of the reading column. */
  var used = {};
  var heads = Array.prototype.slice.call(main.querySelectorAll('h2, h3')).filter(function (h) {
    if (h.closest('.site-foot, .featured-band, .msg-grid, [data-toc="no"]')) return false;
    if (h.classList.contains('unnumbered') || h.id === 'contenido') return false;
    return h.textContent.trim().length > 0;
  });
  heads.forEach(function (h) {
    if (!h.id) {
      var s = h.textContent.trim().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
        .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'sec';
      while (used[s] || document.getElementById(s)) s += '-';
      h.id = s;
    }
    used[h.id] = true;
    var li = document.createElement('li');
    if (h.tagName === 'H3') li.className = 'l3';
    var a = document.createElement('a');
    a.href = '#' + h.id;
    /* This runs before KaTeX has rendered the headings, so a heading with mathematics still holds TeX
       source: copy its markup, including the math spans, and let the page's KaTeX pass render the copy. */
    var copy = h.cloneNode(true);
    copy.querySelectorAll('.katex-mathml, annotation, .anchorjs-link').forEach(function (n) { n.remove(); });
    var label = copy.textContent.trim().replace(/\s+/g, ' ');
    if (copy.querySelector('.math, .math-done, .katex')) a.innerHTML = copy.innerHTML.trim();
    else a.textContent = label.length > 72 ? label.slice(0, 70).replace(/[\s,;:]+\S*$/, '') + '…' : label;
    a.title = label;
    li.appendChild(a);
    toc.appendChild(li);
  });
  if (!heads.length) { document.querySelector('.docs-toc').hidden = true; return; }

  /* 3. Scroll-spy. */
  var items = Array.prototype.slice.call(toc.querySelectorAll('a'));
  function spy() {
    var y = window.scrollY + 120, best = null;
    heads.forEach(function (h) { if (h.getBoundingClientRect().top + window.scrollY <= y) best = h; });
    items.forEach(function (a) { a.classList.toggle('current', best && a.getAttribute('href') === '#' + best.id); });
  }
  window.addEventListener('scroll', spy, { passive: true });
  window.addEventListener('hashchange', spy);
  spy();
})();
</script>
<footer class="site-foot">
  <div class="site-foot__inner">
    <div class="foot-grid">
      <div class="foot-about">
        <h4 class="anchored">What this is</h4>
        <p>The test ledger of difes, a program for dielectric-function models, reflectivity, emissivity, Kramers–Kronig and fitting of infrared spectra, built as a personal project to give the group an open and documented counterpart of FOCUS. Every check the program has passed through is listed here with its grade, its data and its result, next to the validation pages the checks come from and the complete manual: how the app looks and works, and the physics it implements, equation by equation.</p>
        <div class="cite-block">Josu M. Igartua · Departamento de Física, UPV/EHU<br>josu.igartua@ehu.eus</div>
      </div>
      <div><h4 class="anchored">This site</h4><ul>
        <li><a href="../tests/index.html">The test ledger</a></li><li><a href="../validation/index.html">Against FOCUS</a></li><li><a href="../validation/irati-path.html">Irati's path</a></li><li><a href="../validation/papers.html">Published works</a></li><li><a href="../validation/focus-samples.html">FOCUS's sample projects</a></li><li><a href="../validation/literature.html">The literature</a></li><li><a href="../manual/index.html">The manual: using difes</a></li><li><a href="../manual/theory/index.html">The manual: theoretical basis</a></li></ul></div>
      <div><h4 class="anchored">Sources</h4><ul>
        <li><a href="https://doi.org/10.1366/000370207783292163">De Sousa Meneses et al. 2007 (CFRC)</a></li>
        <li><a href="https://doi.org/10.1366/0003702041655467">De Sousa Meneses et al. 2004 (semi-quantum models)</a></li>
        <li><a href="https://doi.org/10.1063/1.1979470">Kuzmenko 2005 (RefFIT, VDF)</a></li>
        <li><a href="https://www.cemhti.cnrs-orleans.fr/pot/software/focus.html">FOCUS at CEMHTI</a></li></ul></div>
      <div><h4 class="anchored">Status</h4><ul>
        <li>A twin of the project site, which is not published yet; the greyed references point to pages of that site</li>
        <li>Regenerated from the same sources on every render</li></ul></div>
    </div>
    <div class="foot-bottom">
      <span>© 2026 Josu M. Igartua</span>
      <span>Quarto · family design kit</span>
    </div>
  </div>
</footer>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>